from lexer import Token, TokenType

fizzbuzz_tokens = [Token(TokenType.FOR), Token(TokenType.LEFT_BRACKET), Token(TokenType.INT),
                   Token(TokenType.IDENTIFIER, "i"), Token(TokenType.IN), Token(TokenType.IDENTIFIER, "nums"),
                   Token(TokenType.LEFT_BRACKET), Token(TokenType.INT, 1), Token(TokenType.COMMA),
                   Token(TokenType.INT, 101), Token(TokenType.RIGHT_BRACKET), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.LEFT_CURLY_BRACKET), Token(TokenType.IF), Token(TokenType.LEFT_BRACKET),
                   Token(TokenType.IDENTIFIER, "mod"), Token(TokenType.LEFT_BRACKET), Token(TokenType.INT, 1),
                   Token(TokenType.COMMA), Token(TokenType.INT, 15), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.EQUALS), Token(TokenType.INT, 0), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.LEFT_CURLY_BRACKET), Token(TokenType.WRITE),
                   Token(TokenType.LEFT_BRACKET), Token(TokenType.STRING, "FizzBuzz"), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.RIGHT_CURLY_BRACKET), Token(TokenType.ELIF), Token(TokenType.LEFT_BRACKET),
                   Token(TokenType.IDENTIFIER, "mod"), Token(TokenType.LEFT_BRACKET), Token(TokenType.INT, 1),
                   Token(TokenType.COMMA), Token(TokenType.INT, 3), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.EQUALS), Token(TokenType.INT, 0), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.LEFT_CURLY_BRACKET), Token(TokenType.WRITE),
                   Token(TokenType.LEFT_BRACKET), Token(TokenType.STRING, "Fizz"), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.RIGHT_CURLY_BRACKET), Token(TokenType.ELIF), Token(TokenType.LEFT_BRACKET),
                   Token(TokenType.IDENTIFIER, "mod"), Token(TokenType.LEFT_BRACKET), Token(TokenType.INT, 1),
                   Token(TokenType.COMMA), Token(TokenType.INT, 5), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.EQUALS), Token(TokenType.INT, 0), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.LEFT_CURLY_BRACKET), Token(TokenType.WRITE),
                   Token(TokenType.LEFT_BRACKET), Token(TokenType.STRING, "Buzz"), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.RIGHT_CURLY_BRACKET), Token(TokenType.ELSE), Token(TokenType.LEFT_CURLY_BRACKET),
                   Token(TokenType.WRITE), Token(TokenType.LEFT_BRACKET),
                   Token(TokenType.IDENTIFIER, "toStr"), Token(TokenType.LEFT_BRACKET),
                   Token(TokenType.IDENTIFIER, "i"), Token(TokenType.RIGHT_BRACKET), Token(TokenType.RIGHT_BRACKET),
                   Token(TokenType.RIGHT_CURLY_BRACKET), Token(TokenType.RIGHT_CURLY_BRACKET)]
